/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 boot.gltf
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Boot(props) {
  const { nodes, materials } = useGLTF("/../src/homepage/boot.gltf");
  return (
    <group {...props} dispose={null} scale={0.01}>
      <mesh
        geometry={nodes.游艇stl.geometry}
        material={nodes.游艇stl.material}
        scale={0.1}
      />
    </group>
  );
}

useGLTF.preload("/../src/homepage/boot.gltf");
