/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Draco.gltf
Author: Terrie (https://sketchfab.com/terrielsimmons)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sakura-cake-roll-9234c6ed4bb048f5a646042c1512b18a
Title: Sakura Cake Roll
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/../src/homepage/Draco.gltf");
  //这里路径和预渲染路径一直即可
  return (
    <group {...props} dispose={null} scale={8}>
      <group rotation={[-Math.PI, 0, 0]} scale={1.9}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.material0000}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.material0000}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.material0000}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.material0000}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/../src/homepage/Draco.gltf");
//(/../src/homepage/Draco.gltf)最开始一个斜杠代表public文件夹，从public文件夹反推到页面文件夹就行
