/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import {
  useGLTF,
  PerspectiveCamera,
  OrthographicCamera,
} from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/../src/homepage/cupboard.glb");
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={false}
        far={877.84}
        near={724.522}
        fov={26.991}
        position={[0.388, 0.258, 0.65]}
        rotation={[-0.278, 0.503, 0.137]}
        scale={0.001}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={374.591}
        near={175.966}
        fov={60.778}
        position={[-0.148, -0.193, 0.084]}
        rotation={[1.19, -0.512, -0.194]}
        scale={0.001}
      />
      <OrthographicCamera
        makeDefault={false}
        far={211.942}
        near={160.729}
        position={[0.051, 0.057, 0.175]}
        scale={0.001}
      />
      <OrthographicCamera
        makeDefault={false}
        far={1982.272}
        near={1858.25}
        position={[-0.01, -1.901, 0.019]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.001}
      />
      <OrthographicCamera
        makeDefault={false}
        far={907.984}
        near={741.342}
        position={[0.825, 0.014, 0.007]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        scale={0.001}
      />
      <group scale={0.1}>
        <group position={[0, 73.023/2, 8.382]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(8B946E54-E5B7-4B3C-B718-49E5579A1CDF)"].geometry
            }
            material={materials["预设值:0:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(E671314D-E563-4B19-9E0A-A07D60EC286B)"].geometry
            }
            material={materials["预设值:0:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(71141D79-7B98-408F-82E1-6E70A4AAAFE5)"].geometry
            }
            material={materials["预设值:0:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(07CB03B6-2BC2-46FC-B667-983DC1572776)"].geometry
            }
            material={materials["预设值:0:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(F6F18CD4-4A4A-4D45-BB38-427B5670AA77)"].geometry
            }
            material={materials["预设值:0:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["柜体(129FFD9C-928E-4B0D-BEC0-AA1C18F9C794)"].geometry
            }
            material={materials["柜体:200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["柜体(E8BD83A0-7FA2-4AE8-8A50-2EB411E77748)"].geometry
            }
            material={materials["柜体:200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["柜体(A3698F43-F492-4C82-8167-D6C361813437)"].geometry
            }
            material={materials["柜体:200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["柜体(858CACB1-25FE-4582-838A-8338829547DA)"].geometry
            }
            material={materials["柜体:200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["柜体(30786570-75C1-4966-8D15-8C717E01D7EA)"].geometry
            }
            material={materials["柜体:200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["柜体(5344DC16-B910-480E-AE05-BDC756DAE325)"].geometry
            }
            material={materials["柜体:200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["柜体(B6D714A4-528F-4D0A-984F-0AF44C1794CD)"].geometry
            }
            material={materials["柜体:200:0:0"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/../src/homepage/cupboard.glb");
