/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import {
  useGLTF,
  PerspectiveCamera,
  OrthographicCamera,
} from "@react-three/drei";

export function Xichenqi(props) {
  const { nodes, materials } = useGLTF("/../src/homepage/xichenqi.glb");
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={false}
        far={2385.05}
        near={1781.038}
        fov={26.991}
        position={[1.343, 0.321, -1.474]}
        rotation={[-2.958, 0.76, 3.014]}
        scale={0.001}
      />
      <OrthographicCamera
        makeDefault={false}
        far={948.41}
        near={184.808}
        position={[0.474, 0.046, 0.054]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.001}
      />
      <OrthographicCamera
        makeDefault={false}
        far={145.599}
        near={53.599}
        position={[0.182, 0.097, 0.11]}
        scale={0.001}
      />
      <OrthographicCamera
        makeDefault={false}
        far={183.008}
        near={91.049}
        position={[0.261, 0.183, 0.032]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.001}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={1000.653}
        near={463.83}
        fov={39.598}
        position={[-0.378, 0.187, 0.694]}
        rotation={[-0.175, -0.631, -0.104]}
        scale={0.001}
      />
      <group scale={0.01}>
        <group position={[88.877, 45.979, 10]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_1.geometry}
            material={materials["吸口 200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_2.geometry}
            material={materials["吸口 200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_3.geometry}
            material={materials["吸口 200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_4.geometry}
            material={materials["吸口 200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_5.geometry}
            material={materials["吸口 200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_6.geometry}
            material={materials["吸口 200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_7.geometry}
            material={materials["吸口 200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_8.geometry}
            material={materials["吸口 200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_9.geometry}
            material={materials["吸口 200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_10.geometry}
            material={materials["吸口 200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_11.geometry}
            material={materials["吸口 200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_12.geometry}
            material={materials["吸口 200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_1.geometry}
            material={materials["操纵杆 125:38:205"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_2.geometry}
            material={materials["操纵杆 125:38:205"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_3.geometry}
            material={materials["操纵杆 125:38:205"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_4.geometry}
            material={materials["操纵杆 125:38:205"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_5.geometry}
            material={materials["操纵杆 125:38:205"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_6.geometry}
            material={materials["操纵杆 125:38:205"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_7.geometry}
            material={materials["操纵杆 125:38:205"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_8.geometry}
            material={materials["操纵杆 125:38:205"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_9.geometry}
            material={materials["操纵杆 125:38:205"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_10.geometry}
            material={materials["操纵杆 125:38:205"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_11.geometry}
            material={materials["操纵杆 125:38:205"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.外壳_1.geometry}
            material={materials["外壳 0:0:255"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.滤嘴_1.geometry}
            material={materials["滤嘴 0:127:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.开关_1.geometry}
            material={materials["开关 255:255:255"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.开关_2.geometry}
            material={materials["开关 255:255:255"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.开关_3.geometry}
            material={materials["开关 255:255:255"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.开关_4.geometry}
            material={materials["开关 255:255:255"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.开关_5.geometry}
            material={materials["开关 255:255:255"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.电子_1.geometry}
            material={materials["电子 255:0:195"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.电子_2.geometry}
            material={materials["电子 255:0:195"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.电子_3.geometry}
            material={materials["电子 255:0:195"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.电子_4.geometry}
            material={materials["电子 255:0:195"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_1.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_2.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_3.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_4.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_5.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_6.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_7.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_8.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_9.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_10.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_11.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_12.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_13.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_14.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_15.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_16.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_17.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_18.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_19.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_20.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_21.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_22.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_23.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_24.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_25.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_26.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_27.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_28.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_29.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_30.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_31.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_32.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_33.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_34.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_35.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_36.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_37.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_38.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_39.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_40.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_41.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_42.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_43.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_44.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_45.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_46.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_47.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_48.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_49.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_50.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_51.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_52.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_53.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_54.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_55.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_56.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_57.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_58.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_59.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.出气口_1.geometry}
            material={materials["出气口 0:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.出气口_2.geometry}
            material={materials["出气口 0:0:0 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.贴图_1.geometry}
            material={materials["贴图 255:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.贴图_2.geometry}
            material={materials["贴图 0:0:255"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/../src/homepage/xichenqi.glb");
