/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export function EscortBoatModel(props) {
  const { nodes, materials } = useGLTF("/model_escort.glb");
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={false}
        far={282.5}
        near={149.925}
        fov={39.598}
        position={[-0.142, 0.068, 0.115]}
        rotation={[-0.513, -0.757, -0.369]}
        scale={0.001}
      />
      <group scale={0.04}>
        <group
          position={[-12.268, -16.346, 62.524]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["图层_01(7144F502-EFEB-467D-BB1B-ABDED4BF61B4)"].geometry
            }
            material={materials["Metal Textured Grey #1"]}
            position={[0, 0.1, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["图层_01(8E76D154-5AD6-4EE0-8C32-96E7A0583820)"].geometry
            }
            material={materials["Metal Textured Grey #1"]}
            position={[0, 0.1, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["图层_01(667DF615-E7AD-423C-86B6-966888FA5B0E)"].geometry
            }
            material={materials["Paint Matte Orange #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["图层_01(6F159D1F-6A7C-4E90-8F36-D476394653F3)"].geometry
            }
            material={materials["Metal Textured Grey #1"]}
            position={[0, -0.1, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["图层_01(97B24D01-12B2-4EB5-9424-D5DA8E9B43FF)"].geometry
            }
            material={materials["Metal Textured Grey #1"]}
            position={[0, -0.1, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["图层_01(F347DF94-36D3-4DC9-AFAE-747E6F59514F)"].geometry
            }
            material={materials["Paint Matte Orange #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["图层_01(52D34920-1D22-4D4E-8126-474843932210)"].geometry
            }
            material={materials["Paint Metallic White #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["图层_01(D3873E8E-3966-42C1-84D5-DD90C66DBDD9)"].geometry
            }
            material={materials["Metal Textured Grey #1"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/model_escort.glb");
