/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export function EscortPlusModel(props) {
  const { nodes, materials } = useGLTF("/model_escortplus.glb");
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={false}
        far={56.381}
        near={25.471}
        fov={49.223}
        position={[0.02, 0.023, 0.034]}
        rotation={[-0.357, 0.507, 0.179]}
        scale={0.001}
      />
      <group scale={0.3}>
        <group
          position={[0.019, 0, 0.234]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(2536C947-D2B1-4973-ADE0-4D4927220B01)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(45B0270E-2775-4640-858C-A98F00EB9FB8)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(4567BB1C-873C-40A3-8DF0-FB3DC9FE89DF)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(98341DA1-09E7-4DF0-B18D-C53BEAC71AB4)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(CF4F646A-EEAF-43AB-903F-60FD7EE263B4)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(CBE57167-9695-455F-B97B-6B4AF8DC3727)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(6D7006F1-E5FA-4FC3-86B4-42F37CE53B29)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(1C26D1C2-A8EA-4546-962E-FC315E9FFA32)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(C2739779-16F8-4C7B-90D8-F4DFA279C056)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(486B8609-38EE-4F90-9C74-B4D9FC2F52D0)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(B4C8437B-3670-4967-A813-A09BC3DB78F0)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(FE40DD0F-8078-4A1C-B6CC-272C16C3A233)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(E968B3FD-A72A-4874-8D06-632D6F2C7315)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(7F498291-066A-43BF-8E59-87A02AD73B98)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(49A5C896-0865-4188-B77E-C5EB8F86D7B3)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(269FBE6B-612F-4187-B3CD-34388EE100B4)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(6E577182-BA8D-4BBB-B5E3-46C2A5B784CA)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(E9FE08BF-052B-4B6B-A48F-6F17018627E3)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(E066E968-AEF6-4F9D-8D9E-4036D928D2A1)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(A9AE4D2A-ADAA-430C-B721-9F543D3B0B11)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(AD427B3F-BFBD-4BFE-AD06-0340994FEC15)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(C6C14556-9C51-45E9-91FF-1656757505B5)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(06D7274C-CC07-494B-A7AC-15D409069108)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(4B57117A-6F6E-4DFA-BBC8-73009E253758)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(DA9F2381-E186-47A0-BFA2-DDE5BAA2DFDB)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(BD64FCC2-516D-442F-AB48-A07A5BD81AB6)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(6410119B-29E0-4404-A9B1-D12D6768A731)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(BCF3447B-E90A-4D5D-AC16-A0B8BE5B2FE6)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(B7EC749B-03FB-4234-93F5-CA6E7A4F118E)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(F708756D-B9DC-4E80-982B-B7F6C8D7DFB5)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(0B9C36AA-0739-4FCA-A341-87E9D0924A9E)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(52B20452-68B7-473E-BD45-DB48CC541094)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(6712949F-316F-4ECB-9A30-9FE41C4AB16A)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(71E3C619-4D98-41E7-A58C-CAE69FC0B7F6)"].geometry
            }
            material={materials["Chrome Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(E9D66B7A-4AE3-4399-8D1D-90398751EFB7)"].geometry
            }
            material={materials["Paint Matte Orange #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(27D7631A-49F8-48B3-93CD-3BA46E8B88CF)"].geometry
            }
            material={materials["Paint Gloss White #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(2531FAF3-C633-402C-B0D1-192FC7105B16)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(37E14AE2-6059-4BBC-A739-21BC236CEC3A)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(A78C978B-FFD4-4FA6-BBA2-A55AEBF60D2C)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(986DDC61-49AE-4E0D-A903-62855DD382FC)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(6CF2D2BE-1234-4658-B7FC-7E662612704A)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(0ED7DAC8-B5F5-4FCB-956D-F9A92E763079)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(467B89F4-7F7C-4684-9D4C-6717844E0CCC)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(8A9DE0C7-932B-43C7-877A-B1E6FE98A1F6)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(4AAEE853-9D91-4692-8A0D-ADF1FF058317)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(404C27FC-2726-4491-A3C0-E94C6D6E2F52)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(D39B0778-69DA-4D96-ADE4-B66676832297)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(73FA25F0-2DFF-4476-AE29-5F7E27C79A59)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(C6D17808-A7CE-4C99-80A0-DA456415CD2B)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(C219AA2F-C083-4E1E-A731-E8A26CFFA080)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(950D9C07-116B-42D7-AF30-13D866C4F59E)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(54CDF84D-F11C-430B-94EF-2287C475094F)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(4BC1AF5B-425E-4666-964C-83F919FC02BF)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(F936CC4C-9930-443F-82E3-5A50857541AC)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(C1FE6D7B-FF31-495F-AD9D-48FCF3BDC494)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(A5FCD94A-7C75-4685-8F54-EC2323E3419D)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(B53BAD18-29C6-43E8-9E1A-B94B5491BDBD)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(DC2EBB23-DAB2-492B-B8E0-5C8835BA1B9D)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(454547BA-3340-45F1-BDAC-64A839438924)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(A40B742D-BE7D-447C-BF1E-661E821D7E5E)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(1C9A1E97-6EB2-4DC1-8609-AE53B5C28971)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(64CA57C7-4952-4514-9790-FAB88DDBCF8B)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(0E9F4CA4-2F49-4D01-9F35-51D42996D213)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(1F8FB389-E9EC-4F37-AFF0-992491259DBD)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(5CE20C2E-2D0D-449E-AC8B-9F3B4C953FED)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(E9C4B913-A757-4EC6-A5B9-2F796655D5F1)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(D1790B3A-0F82-4217-ABBC-1B36B191A8F1)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(020D33DA-340D-461F-B43A-D4B250979A5E)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(9DAE3E2B-FA6D-4B57-92E6-B7876A5EC613)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(A3F140E2-E3A9-4A9F-A519-FF8C1338B9DF)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(5E403D30-2DD1-4868-BB88-BF6239FBFE13)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(4C7AE8FC-1D2F-4F01-9C11-8E5E54529BDD)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(437F527C-1135-4236-A1F0-0D05D763EF3A)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(AF73B69A-C83E-45E5-8ABB-DD360B06404A)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(30ED0281-0F80-4F7F-80CF-614F32FB723F)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(80F51BC9-D2B7-4488-84A0-C892DE914A22)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(586AC608-57B0-4C08-92AF-535BE9E9DC47)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(B0EFD561-25CA-4004-B000-78D8F59CEEFF)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(C84FA542-914F-46A0-B8B4-402BCB5B0E62)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(72CE6406-00DE-456C-A14D-1F232A051406)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(41D9440E-9B20-4A23-A117-55598AE93DE0)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(0DC2F7F5-B93F-43F8-B542-7A875C571F68)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(35403379-0AE1-4E30-8BB2-33549D701BF3)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(49420241-D32E-4379-91C5-F5B4B1C6D5EB)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(78AC9E6B-D98A-4510-82C8-9630F30B0974)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(4A9D519C-75BB-46AF-A72B-D34FA6298C39)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(D747D445-02BD-4456-B7CC-4CFCF66CEC42)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(A2D76BE3-0F76-4D3C-9609-8B8EB805975D)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(04CE499E-805F-419C-A5D3-79D1FBCFA334)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(C4D3FA82-15B1-41B0-BE19-C3D6DC1C7812)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(F7F5EF72-429D-4715-BF19-8F3691E7BFC1)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(0550F1C0-9C1C-4C97-A5B4-9987781BB318)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(5D3C0739-87FF-4834-A723-CEFFA3FD279B)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(15DDB1F8-6FB0-4C1C-9AC3-271A41859B9C)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(EFF20209-E749-4915-B33B-019C4279470F)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(F65D6424-0452-473B-9F3A-F95055F7F81A)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(F3A0EACC-0CCC-44D1-A38A-C45CBB2686C6)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(16A6FC0B-6C30-4098-8BF3-7B5B80C15035)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(57C87592-DC53-484B-ABAB-B41314F923E6)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(8DBB5804-7A90-4B72-85FD-5C551FDF9B5F)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(75FE9A5B-756D-4474-B66A-44A22B3CD46C)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(27EFAA61-0483-4EE2-A14A-16EC5B46E9C4)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(9DE70B09-06D4-4023-A4EF-BC3B587F1367)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(E2F6C156-509E-4460-96C4-4B0B358A0CA6)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(3751ED39-FF52-4750-BBA6-0F3CD6C2804F)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(1A5FE3B0-9E9F-4178-A56A-D84FB02129B2)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(A8324F48-7643-40EE-ADCF-D841848C294B)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(1FF8149B-06E4-456C-889E-6BA1A6188740)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(9A890CD6-059F-4CFA-8CA5-0B4769AE8A5C)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(05C0E798-AB63-4350-B49B-6E73B4D6BD85)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(D82E1BEA-2CE5-4F51-BE96-231267E88F2E)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(B8C3C0F9-7159-4509-9F5A-5E26C2E0301F)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(8AC56E90-BD01-430D-B0D6-223E28BCCFAF)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(6F0DAC2F-8291-48A3-AEF8-5A77FAAF26DC)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(B5449660-75DC-428E-ABC6-5A6F7997EEBE)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(753B1149-3C2E-4392-819A-665A0EED27E0)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(8DF4F2F1-710C-4D13-9B5B-9DD76B6B4C44)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(2330B01E-C03A-46DE-B71E-119D12D8D76A)"].geometry
            }
            material={materials["Paint Gloss White #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(A9F28068-B414-4934-8F1F-EF3665D77604)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(66D058C1-0DE8-48AD-BDCE-BD9ED174582E)"].geometry
            }
            material={materials["Paint Textured Red #1"]}
          />
        </group>
        <group
          position={[0.019, 0, 0.234]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(559A4FAF-E04B-4D31-BF62-C551436EF6B2)"].geometry
            }
            material={materials["Paint Matte Orange #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["整体图(C7BF3990-718A-4889-ACD3-A2963AB90D3E)"].geometry
            }
            material={materials["Paint Matte Orange #1"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/model_escortplus.glb");
