/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export function MissCalenderModel(props) {
  const { nodes, materials } = useGLTF("/model_misscalender.glb");
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={false}
        far={1245.273}
        near={763.169}
        fov={36.515}
        position={[0.898, 0.348, -0.368]}
        rotation={[-2.44, 1.106, 2.494]}
        scale={0.001}
      />
      <group scale={0.016}>
        <group position={[9.5, 0, -14.051]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["触点1(40F94EFA-08D8-425E-8F9B-38D1EE1226B6)"].geometry
            }
            material={materials["Metal Rough Blue #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["触点1(CA5C35BA-D36D-45BC-B414-1F770D408CF4)"].geometry
            }
            material={materials["Metal Rough Blue #1"]}
            position={[0, -152.87, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["触点2(54252F50-77A5-4DF3-9AC6-CD739A7B062D)"].geometry
            }
            material={materials["Metal Rough Green #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["触点2(72CD76DC-FED5-4CBD-A7DA-5B07B04B4E17)"].geometry
            }
            material={materials["Metal Rough Green #1"]}
            position={[0, -152.87, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["触点3(5D2356DA-787B-493D-B8FA-F9926C2DA50D)"].geometry
            }
            material={materials["Aluminum Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["触点3(992BAE08-253D-4DC5-B91F-2BB218831BE3)"].geometry
            }
            material={materials["Aluminum Rough #1"]}
            position={[0, -152.87, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["触点4(CF34C095-2C5B-426D-925B-3A332DCE4B64)"].geometry
            }
            material={materials["Metal Rough Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["触点4(D6648789-A2CC-4829-8DFD-57EB23EFB7FC)"].geometry
            }
            material={materials["Metal Rough Red #1"]}
            position={[0, -152.87, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["触点1(BF4FEA2D-B231-4C4A-95F0-8D411BCC4597)"].geometry
            }
            material={materials["Metal Rough Blue #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["触点1(2EFF2B54-CC65-4342-875B-6069C7E021AB)"].geometry
            }
            material={materials["Metal Rough Blue #1"]}
            position={[0, 179.414, -20]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["触点2(50B7B818-6509-4286-8FAC-6FB6BAC1F9EC)"].geometry
            }
            material={materials["Metal Rough Green #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["触点2(CC84B85B-E009-4C3D-9946-563B127FD6A7)"].geometry
            }
            material={materials["Metal Rough Green #1"]}
            position={[0, 179.414, -20]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["触点3(2503B3B5-2F81-4B96-9FE0-A55D48AFD390)"].geometry
            }
            material={materials["Aluminum Rough #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["触点3(62EE53BB-2712-461C-92D5-FAA8359DE629)"].geometry
            }
            material={materials["Aluminum Rough #1"]}
            position={[0, 179.414, -20]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["触点4(5845A073-F40C-4580-8014-A211689F95C5)"].geometry
            }
            material={materials["Metal Rough Red #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["触点4(B6BB6F98-0C35-4508-8F49-356B3EBC4315)"].geometry
            }
            material={materials["Metal Rough Red #1"]}
            position={[0, 179.414, -20]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["壳(586AB3E5-2E3E-4724-AD81-733462F689DF)"].geometry
            }
            material={materials["Paint Gloss White #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["壳(E7E26201-B2B5-4595-A1F5-FB3C9D72D7EC)"].geometry
            }
            material={materials.面板}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["壳(BFE8B214-6F0F-40A7-B7E2-39DF67CBC404)"].geometry
            }
            material={materials["Paint Gloss White #1"]}
            position={[24.379, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["壳(233BE3EA-20D4-435D-929D-E2374D425728)"].geometry
            }
            material={materials["Paint Gloss White #1"]}
            position={[0, -152.87, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["壳(D748B48C-BE3E-434B-A3D2-83324A9A0FE0)"].geometry
            }
            material={materials.面板}
            position={[0, -152.87, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["壳(F1C467EC-24E8-4374-80B0-E0D316CD679B)"].geometry
            }
            material={materials["Paint Gloss White #1"]}
            position={[0, 179.414, -20]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["壳(0CB41143-ECF8-42AC-BD93-C98B9650D7B2)"].geometry
            }
            material={materials.小面板}
            position={[0, 179.414, -20]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/model_misscalender.glb");
