/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export function NotlackModel(props) {
  const { nodes, materials } = useGLTF("/model_notlack.glb");
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={false}
        far={873.661}
        near={459.305}
        fov={39.598}
        position={[-0.536, 0.419, 0.215]}
        rotation={[-1.077, -0.832, -0.942]}
        scale={0.001}
      />
      <group scale={0.03}>
        <group position={[-20, 0, 90.5]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.外壳_1.geometry}
            material={materials["外壳 0:0:0 #10"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.外壳_2.geometry}
            material={materials["外壳 0:0:0 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.外壳_3.geometry}
            material={materials["外壳 0:0:0 #10"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.外壳_4.geometry}
            material={materials["外壳 0:0:0 #10"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.外壳_5.geometry}
            material={materials["外壳 0:0:0 #10"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.磁条_1.geometry}
            material={materials["磁条 0:0:0 #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.内壳_1.geometry}
            material={materials["内壳 0:0:0 #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.内壳_2.geometry}
            material={materials["内壳 0:0:0 #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.拉绳_1.geometry}
            material={materials["拉绳 0:0:0 #3"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/model_notlack.glb");
