/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export function OnesurfaceModel(props) {
  const { nodes, materials } = useGLTF("/model_onesurface.glb");
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={false}
        far={1769.697}
        near={701.895}
        fov={54.432}
        position={[-1.008, 0.435, 0.641]}
        rotation={[-0.39, -0.925, -0.317]}
        scale={0.001}
      />
      <group scale={0.006}>
        <group position={[0, 50, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_1.geometry}
            material={materials["Liquid Water"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_2.geometry}
            material={materials["Paint Matte White"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_3.geometry}
            material={materials["Paint Matte White #5"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_4.geometry}
            material={materials["Paint Matte White #5"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_5.geometry}
            material={materials["Paint Matte White #5"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_6.geometry}
            material={materials["Paint Matte White"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_7.geometry}
            material={materials["Liquid Water"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_8.geometry}
            material={materials["Paint Matte White #5"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_9.geometry}
            material={materials["Paint Matte White #5"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_10.geometry}
            material={materials["Paint Matte White #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_11.geometry}
            material={materials["Paint Matte White"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_12.geometry}
            material={materials["Aluminum Polished"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_13.geometry}
            material={materials["Paint Matte White #5"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_14.geometry}
            material={materials["Paint Matte White #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_15.geometry}
            material={materials["Paint Matte White #5"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_16.geometry}
            material={materials["Paint Matte White #5"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_17.geometry}
            material={materials["Paint Matte White #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_18.geometry}
            material={materials["Paint Matte White"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_19.geometry}
            material={materials["Paint Matte White"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_20.geometry}
            material={materials["Paint Matte White"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_21.geometry}
            material={materials["Paint Matte White #21"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_22.geometry}
            material={materials["Paint Matte White #5"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_23.geometry}
            material={materials["Liquid Water"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_24.geometry}
            material={materials["Paint Matte White #5"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_25.geometry}
            material={materials["Paint Matte White"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_26.geometry}
            material={materials["Paint Matte White"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_27.geometry}
            material={materials["Aluminum Polished"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_28.geometry}
            material={materials["Paint Matte White #5"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_29.geometry}
            material={materials["Aluminum Polished"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_30.geometry}
            material={materials["Paint Matte White"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_31.geometry}
            material={materials["Paint Matte White #5"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_32.geometry}
            material={materials["Paint Matte White"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_33.geometry}
            material={materials["Paint Matte White"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_34.geometry}
            material={materials["Paint Matte White"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_35.geometry}
            material={materials["Paint Matte White #5"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_36.geometry}
            material={materials["Aluminum Polished"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_37.geometry}
            material={materials["Paint Matte White"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_38.geometry}
            material={materials["Paint Matte White #5"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_39.geometry}
            material={materials["Paint Matte White #5"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_40.geometry}
            material={materials["Paint Matte White #5"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_41.geometry}
            material={materials["Liquid Water"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_42.geometry}
            material={materials["Paint Matte White #1"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/model_onesurface.glb");
