/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export function VectorModel(props) {
  const { nodes, materials } = useGLTF("/model_Vector.glb");
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={false}
        far={2656.321}
        near={1756.502}
        fov={26.991}
        position={[1.604, 0.762, -1.115]}
        rotation={[-2.559, 0.807, 2.697]}
        scale={0.001}
      />
      <group scale={0.001}>
        <group
          position={[101.319, 45.979, -125.322]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_1.geometry}
            material={materials["吸口 200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_2.geometry}
            material={materials["吸口 200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_3.geometry}
            material={materials["吸口 200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_4.geometry}
            material={materials["吸口 200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_5.geometry}
            material={materials["吸口 200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_6.geometry}
            material={materials["吸口 200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_7.geometry}
            material={materials["吸口 200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_8.geometry}
            material={materials["吸口 200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_9.geometry}
            material={materials["吸口 200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_10.geometry}
            material={materials["吸口 200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_11.geometry}
            material={materials["吸口 200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_12.geometry}
            material={materials["吸口 200:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_1.geometry}
            material={materials["操纵杆 125:38:205"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_2.geometry}
            material={materials["操纵杆 125:38:205"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_3.geometry}
            material={materials["操纵杆 125:38:205"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_4.geometry}
            material={materials["操纵杆 125:38:205"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_5.geometry}
            material={materials["操纵杆 125:38:205"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_6.geometry}
            material={materials["操纵杆 125:38:205"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_7.geometry}
            material={materials["操纵杆 125:38:205"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_8.geometry}
            material={materials["操纵杆 125:38:205"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_9.geometry}
            material={materials["操纵杆 125:38:205"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_10.geometry}
            material={materials["操纵杆 125:38:205"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_11.geometry}
            material={materials["操纵杆 125:38:205"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.外壳_1.geometry}
            material={materials["外壳 0:0:255"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.滤嘴_1.geometry}
            material={materials["滤嘴 0:127:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.开关_1.geometry}
            material={materials["开关 255:255:255"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.开关_2.geometry}
            material={materials["开关 255:255:255"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.开关_3.geometry}
            material={materials["开关 255:255:255"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.开关_4.geometry}
            material={materials["开关 255:255:255"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.开关_5.geometry}
            material={materials["开关 255:255:255"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.电子_1.geometry}
            material={materials["电子 255:0:195"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.电子_2.geometry}
            material={materials["电子 255:0:195"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.电子_3.geometry}
            material={materials["电子 255:0:195"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.电子_4.geometry}
            material={materials["电子 255:0:195"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_1.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_2.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_3.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_4.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_5.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_6.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_7.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_8.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_9.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_10.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_11.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_12.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_13.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_14.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_15.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_16.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_17.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_18.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_19.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_20.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_21.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_22.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_23.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_24.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_25.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_26.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_27.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_28.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_29.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_30.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_31.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_32.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_33.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_34.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_35.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_36.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_37.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_38.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_39.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_40.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_41.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_42.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_43.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_44.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_45.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_46.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_47.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_48.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_49.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_50.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_51.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_52.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_53.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_54.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_55.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_56.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_57.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_58.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_59.geometry}
            material={materials["风机 255:191:191"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.出气口_1.geometry}
            material={materials["出气口 0:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.出气口_2.geometry}
            material={materials["出气口 0:0:0 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.贴图_1.geometry}
            material={materials["贴图 255:0:0"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.贴图_2.geometry}
            material={materials["贴图 0:0:255"]}
          />
        </group>
        <group
          position={[263.957, 45.979, 125.322]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_14.geometry}
            material={materials["吸口 200:0:0 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_15.geometry}
            material={materials["吸口 200:0:0 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_16.geometry}
            material={materials["吸口 200:0:0 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_17.geometry}
            material={materials["吸口 200:0:0 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_18.geometry}
            material={materials["吸口 200:0:0 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_19.geometry}
            material={materials["吸口 200:0:0 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_20.geometry}
            material={materials["吸口 200:0:0 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_21.geometry}
            material={materials["吸口 200:0:0 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_22.geometry}
            material={materials["吸口 200:0:0 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_23.geometry}
            material={materials["吸口 200:0:0 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_24.geometry}
            material={materials["吸口 200:0:0 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.吸口_25.geometry}
            material={materials["吸口 200:0:0 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_13.geometry}
            material={materials["操纵杆 125:38:205 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_14.geometry}
            material={materials["操纵杆 125:38:205 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_15.geometry}
            material={materials["操纵杆 125:38:205 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_16.geometry}
            material={materials["操纵杆 125:38:205 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_17.geometry}
            material={materials["操纵杆 125:38:205 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_18.geometry}
            material={materials["操纵杆 125:38:205 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_19.geometry}
            material={materials["操纵杆 125:38:205 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_20.geometry}
            material={materials["操纵杆 125:38:205 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_21.geometry}
            material={materials["操纵杆 125:38:205 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_22.geometry}
            material={materials["操纵杆 125:38:205 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.操纵杆_23.geometry}
            material={materials["操纵杆 125:38:205 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.外壳_3.geometry}
            material={materials["外壳 0:0:255 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.滤嘴_3.geometry}
            material={materials["滤嘴 0:127:0 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.开关_7.geometry}
            material={materials["开关 255:255:255 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.开关_8.geometry}
            material={materials["开关 255:255:255 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.开关_9.geometry}
            material={materials["开关 255:255:255 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.开关_10.geometry}
            material={materials["开关 255:255:255 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.开关_11.geometry}
            material={materials["开关 255:255:255 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.电子_6.geometry}
            material={materials["电子 255:0:195 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.电子_7.geometry}
            material={materials["电子 255:0:195 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.电子_8.geometry}
            material={materials["电子 255:0:195 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.电子_9.geometry}
            material={materials["电子 255:0:195 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_61.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_62.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_63.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_64.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_65.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_66.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_67.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_68.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_69.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_70.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_71.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_72.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_73.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_74.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_75.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_76.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_77.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_78.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_79.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_80.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_81.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_82.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_83.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_84.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_85.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_86.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_87.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_88.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_89.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_90.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_91.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_92.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_93.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_94.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_95.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_96.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_97.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_98.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_99.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_100.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_101.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_102.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_103.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_104.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_105.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_106.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_107.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_108.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_109.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_110.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_111.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_112.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_113.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_114.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_115.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_116.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_117.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_118.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.风机_119.geometry}
            material={materials["风机 255:191:191 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.出气口_4.geometry}
            material={materials["出气口 0:0:0  #2"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.出气口_5.geometry}
            material={materials["出气口 0:0:0  #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.贴图_4.geometry}
            material={materials["贴图 255:0:0 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.贴图_5.geometry}
            material={materials["贴图 255:0:0 #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.贴图_6.geometry}
            material={materials["贴图 0:0:255 #1"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/model_Vector.glb");
