/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export function PropellerModel(props) {
  const { nodes, materials } = useGLTF("/mono_ropeller.glb");
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={false}
        far={223.512}
        near={153.43}
        fov={54.432}
        position={[-1.878, 0.322, -0.348]}
        rotation={[3.003, -1.501, 3.003]}
        scale={0.01}
      />
      <group scale={0.05}>
        <group position={[-0.492, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_1.geometry}
            material={materials["Copper Polished"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_2.geometry}
            material={materials["Copper Polished"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_3.geometry}
            material={materials["Copper Polished"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_4.geometry}
            material={materials["Copper Polished"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_5.geometry}
            material={materials["Copper Polished"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_6.geometry}
            material={materials["Copper Polished"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.预设值_7.geometry}
            material={materials["Copper Polished"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/mono_ropeller.glb");
