/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export function ReticuleModel(props) {
  const { nodes, materials } = useGLTF("/mono_Reticule.glb");
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={false}
        far={83787.703}
        near={63321.871}
        fov={39.598}
        position={[-66.915, 22.098, 22.936]}
        rotation={[-0.557, -1.186, -0.524]}
        scale={0.001}
      />
      <group scale={0.00015}>
        <group
          position={[0, 2000, -561]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1000}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(BB843BBF-BE0C-4B55-8C0E-1F53FC392199)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(3139677E-DB1D-4414-99A1-3B2EA290DD26)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(48023980-98E9-4FA9-9462-333890B9A374)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(20FAD091-5042-4DB0-9542-EF68D3EA38BF)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(2060719A-AAFA-4A30-88B3-57D65566912A)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(F154D83D-B33F-4723-9CB4-E4D1C23A1EB0)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(258AED3E-2FDF-4A21-9A4B-8075CBCB223C)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(12FDC05C-E599-4C1C-BAC0-E9CBF80DDCE7)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(EA015AC2-C4F4-4850-A46D-A6BDE08B7B6E)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(115DE852-B96D-48DA-8253-1AA5E7EB092D)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(4FBCC7E7-FB9C-4B2C-A434-B673C635CD11)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(221C627F-681B-4204-AC7B-D22F283FA090)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(9BCE3CE5-5B52-48BE-9DBC-F3333B87120B)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(C77E5BC4-82FE-4855-9632-D9747DDE8ADD)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(55936E6B-016E-4763-B162-B5F2871A74D4)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(53E70217-1B47-4050-8BA2-A4BB0B90C928)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(30EB0B90-4605-4D39-83E3-6D2A9D98C25B)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(D3D79809-2B25-49B3-92BD-3723C2DA1C90)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(2264811F-46D0-400D-966B-C0F109460184)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(0495D465-79F0-494C-8D82-3814793604BB)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(D0EA173F-8EA8-481B-B27E-CB9001FC7636)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(CA859986-4CD9-4F0B-BF25-7C1B8B09EE08)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(F8E2D940-20E4-4AC3-A627-2A380DFAC4A0)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(0EBB6D30-369A-42D5-A0E1-82403825E69B)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(EE3D8166-9D01-47E3-86DF-5356F61E743C)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(5D170BAE-0F6C-4A3F-96AF-0FAD5163459B)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(6623BD27-1FD2-4AA9-BB60-ED2D6035E855)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(78564BE4-C707-4E73-B26B-F6377AA6EAA7)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(9BAF7BD6-86BA-44C6-94B3-B34D03CABDE6)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(4900E626-A606-45FB-B732-ED53BF42F5C1)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(0C3A189E-AD6A-4DF4-8D73-3966B15C6C5A)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(3C563A13-A9D6-4F09-B35A-BE4E8960F004)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(B8C14466-55E3-447B-B5E7-F22A28FE1A88)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(5EAB9FA4-B8D8-4D38-A795-9CC5DD9630B9)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(5BAD10A8-9B20-4430-9D91-BDC1427D150A)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(34F45FB4-426E-4105-9419-649E3666982D)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(2CF345AD-EE7E-4FEC-9D40-D028CB546B31)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(42EF987A-FCAB-4CB3-A80A-CE194E27C1D5)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(C713A2A2-A93F-4618-A140-C8BAC7B6C196)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(9B0782E4-5F6C-466D-A350-2288F6EB3884)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["Default(994C60C1-DA5C-4B9D-8DDB-ACABF8798711)"].geometry
            }
            material={materials["Paint Matte White #3"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/mono_Reticule.glb");
