/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export function WillinsertModel(props) {
  const { nodes, materials } = useGLTF("/mono_willinsert.glb");
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={false}
        far={357.992}
        near={228.42}
        fov={39.598}
        position={[-0.182, 0.116, 0.217]}
        rotation={[-0.336, -0.67, -0.214]}
        scale={0.001}
      />
      <group scale={0.03}>
        <group position={[0, 10, -40]}>
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(E76286F9-FBD9-4E23-AD14-3139590B5519)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(723D47A1-AA7D-4350-9C45-1CE4D189047F)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(3E2BE702-3FEC-446C-8BA5-46BABFBC1053)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(2D06B97F-7BBD-4132-8ACA-55ED103D356F)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(6189E48B-7EB3-4E26-8A14-8AA0AFB31BD1)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(1047DAE0-A47B-49A8-A113-249EC4101F45)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(73E102B8-A9C1-452F-A805-102A52D98959)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(558E7C98-EA9C-4618-AF57-BDC59003903F)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(541814CF-CC31-405F-A345-8DB041830AED)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(43C8EEA2-A763-4843-ABB4-4FA7FFFAA857)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(7E3EBE71-30A1-4AC3-9F71-11D2E85AC836)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(43152748-46BA-4869-BA2C-650B9022B424)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(54312B9D-6BFB-4AA9-A29A-5714CD3C6491)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(E7DE71BB-C184-4F78-B1F4-BD20FB071438)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(3402824C-F493-41DF-A21A-95BDD3FE14F0)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(B2B15075-ED90-409C-8A78-F000B6CB0558)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(DB2FE260-6280-4ED9-9D5F-18EAB7933CEB)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(14A43A32-4694-47E8-A16E-E5C4747BFE46)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(941ED9D4-4A0E-4DDD-98D0-7F6638DA0972)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(4B55C4FC-D9CA-4188-8DE5-A85AF2126657)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(EE062F10-B733-4C32-925A-3EA472B618C0)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(AE0D7A84-4D12-4042-B37F-4C7F36563032)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(71EB5DDE-4356-4EE3-9A20-05761E56C6A6)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(0086F4A3-681D-44D6-A095-60DDF54280B4)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(5CAB5409-61FF-47A2-B226-B4022CDFC504)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(6C0402BC-F57B-4B56-8491-382F91D82249)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(05058AED-6686-48F3-B648-0FFA8AD92622)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(24B3B5BF-3C8E-4B10-BB45-9B0ADEC209D0)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(2DBAB059-2EC8-49A6-8625-CEFA0C155AFF)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(62DE1F45-0E30-4B8A-8AC5-945F8A80FB25)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(C7C21265-1F16-4FEE-85BC-476BEBA622EC)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(11FA2326-BAFA-4737-82B9-6801C6B66AA1)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(0E4A47F3-F183-4733-AE41-B26D22FFBE22)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(E0345875-C608-4891-93A3-028A86CCE48E)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(89C6CFB6-75F6-470A-83B7-C6F2F2A08D2B)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(F6F66E93-39A3-4E76-84A9-9FF03F30522F)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(20D805D2-167F-4008-A2A3-931FCAD6B598)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(59F0A5F7-8E15-44F2-B4AD-008836B8A077)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(C9DD7586-8D13-4A1B-8AD5-8E5A329C062A)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(9F42759A-BB6F-4FEF-A4A7-8384B65A6F8C)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(79F28A75-995C-4C53-9FF6-47D86DF4CB60)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(031D0219-BA4D-492D-9E8A-8AEFFACA1CAB)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(ED3958F6-CD15-41DF-9B25-EBC85208BD6B)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(958C9A35-5C58-455D-BDD1-E4CD08919B3F)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(0FA4DDAC-23D9-45B7-B474-9CECDAD5005C)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(6DCF214E-2554-440F-BC44-0B50E504B851)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(3AEEEDB0-E6A5-447B-906D-9F2065AB404D)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(9633701C-4C75-47A9-BB48-39E806F7B1A9)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(E7F47E99-3F3D-4C75-B0B5-0D6EF63C9250)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(C3A7AC58-99F4-41CB-A4BE-04D5F38098BE)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(2969D1D3-1B35-4153-8E99-CD4AC7309253)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(BCC93C1D-58A0-48C5-A29B-C767D032201D)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(D5D991A1-8BED-4DE0-B973-29AF432C53A6)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(1FFFAED6-5E16-47C4-A05A-FD1EF21DC1C7)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(386CA58A-E9B1-41A4-80E8-1B231BAF1010)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(0249B526-C778-4B3A-8A1A-005C2736170C)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(8D1949F0-B0AB-4243-B613-EE99B736635B)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(38B44DE1-6F6B-4BD1-808F-91AAA8C3038C)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(906828D0-B8C1-472A-B16B-C622CB5453C8)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(EAAF47B8-556E-4C72-AB6A-FC6D6F56B9C3)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(9ACC0502-57EE-421E-AF7F-2F134AE36CCE)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(86F3A105-BFDF-4A2B-9E3E-2D4007BDCAF9)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(B472A967-070E-4E08-950D-47BA8F6C57E0)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(4F247EBB-CF57-4756-8512-C9021644F85C)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(C79B0809-6DB1-4422-B8DB-154296A40B75)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(8022262A-8DC3-4627-95B6-66773517375A)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(46580B19-67B3-4F1B-B589-ADAABE684779)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(28D51084-AB99-4185-A174-2D744209EA58)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(02EC64C6-45F7-4008-A8AA-98FC95697244)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(65BA6D0C-7833-46CD-9BA9-330A53F7D881)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(B733BFAF-5285-4A8C-B85C-89CFE54FB242)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(46F8D677-5A24-4128-89E7-5CCC7E8C82B3)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(57DC79E3-7585-4AFF-A2CD-614EE8939A4E)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(AC0E6992-921B-42BF-AEA5-915DECEABCAF)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(2B521D56-50CD-46AD-B95D-5C40D50C534B)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(A009B1A4-5F56-4DDB-A029-F4DC130134CD)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(769EBE62-4BF4-4FDA-B45B-58F3EAE07991)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(30CD0E61-7EFF-4390-A5EF-8864CA6023AE)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(F870E99F-6BB5-47DE-8807-FE33C34353B7)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(862CD915-FD29-493B-9C31-5317EC69BC67)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(CCE07E27-5073-44DA-8DEC-18A6DF98E58B)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(AED7B291-EC25-4BB5-A681-3C1A70205208)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(15463EFD-1EA0-4D80-87DD-EC96BC3C91A8)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(2761D28D-BAEF-4AE8-9E95-768427C79432)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(3FD0D90A-AA40-4BE6-A14B-F70C729A52DE)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(171CA6B1-4535-4360-BD97-2247A4FECE5F)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(857F9A67-64AB-4C79-A4AF-46E847AE45F8)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(CE46E610-2395-4DC0-AD07-B60C1C093B91)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(9C336BC2-95EB-40E2-B611-1706C40F7EA7)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(FACB3C19-98A4-4698-9A6C-0BD2AC96D25A)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(FB304ED5-0E59-49AB-BF8D-363921860FB5)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(9C967F07-C53E-4C20-BF39-92EE79E0F038)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(A7A5FC74-29A0-4F3A-91A8-50D8F8597A82)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(671F0985-FB17-4E5A-8FC7-1B8A076AA0CD)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(95E9D0CC-C856-4455-849F-13977755C8D8)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(A44E643C-C04D-4397-BF48-FA69470FB12A)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(4DA4511A-FE5C-4C1F-B70A-A331205D7AF9)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(2AA5F2E1-58E5-44F8-9C91-5126D26766F7)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(79CE5953-7498-4369-8B5D-A4BBDF1BBEDE)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(879EA1C4-7F10-4959-9EB9-83D94ADEFB51)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(C263A939-614E-48F3-AE93-B5C0D186410F)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(C4313F42-22AF-465E-A346-3EC94D20B74E)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(8DBA01DE-C2AD-4277-B849-CCB64A9F37E4)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(4131F57B-432E-41E7-8357-FDEB8BBEFFC8)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(81DD0F5D-DFB9-4661-947E-A0009C140263)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(DE360E8F-4411-4BA7-BE8E-225A849C9E17)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(F0A6AD19-A537-4180-86A5-5FFDD3DC369A)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(CD88BDAA-65A0-4D4D-B6E3-84CC3B160460)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(B6971F8A-2362-4E51-BD11-BBA1AD693FB1)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(50EAAA94-3787-4C91-B701-A396239F5C39)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(DCAE2BB5-DBBE-4376-A19E-15EEE24AE097)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(5AD61D98-F377-4B5F-BFDA-913CD19753F9)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(19C53E4A-16D2-4F38-AEDE-19D768B3D4FF)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(570B0E8C-09C3-4604-BF0B-9A9082C13284)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(877B3B64-4292-4055-BD20-C44B0AE9C219)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(94257685-A88A-4453-8955-915D80D85FE0)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(7998C475-3CAD-4842-8867-80679176F68A)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(F6DA456B-C876-4E1D-B70C-7976FCD25811)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(4ABA9F66-358B-4AD3-AA28-12F0188A6CCC)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(C6DF4AC5-126C-4049-AA9E-EEAA9491B0BA)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(B8D36875-D1D5-46EB-A129-0ABBC7999603)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(ADFB507E-1890-403F-973D-A94B54BCF812)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(650F343B-3329-47F0-9C01-546EF06B0D77)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(46A87261-51A1-4744-8B1D-06A742C5542C)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(387F5E78-2EC7-445B-86C6-A377071E231C)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(188F9EE4-08CF-40B4-8964-B5A6275EA08F)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(0D853B7F-3C09-497E-874E-91CBC599E5B6)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(1390726C-30B2-436B-A022-8475075E5525)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(732905C4-DB12-45C8-947D-07B70E47EF27)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(270F99D3-6773-4E77-B88D-99004C7AA637)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(4297FDE5-7525-4EA7-9E25-FF1B5859EDBA)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(0C9A6B88-2719-4F7D-82FB-45686B199E8D)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(8E169DC7-952E-481F-9486-2C0AF8AA2C26)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(E82AA022-ED12-4121-9D30-1BE5DED221B8)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(052D588F-B551-4684-A634-CB03B9D994C2)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(82FD6990-F19B-4087-966C-DB828A3C4772)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(E603D9A1-579D-46BE-87D7-58263123D653)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(B57E091E-206F-4537-8EEC-7987EB57DC19)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(ECFB0EE2-958E-41D1-BEC4-4AEBE8879A2C)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(8026942B-AC21-4692-9671-908067F587D4)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(6B1A2AF1-A3DD-4601-9D75-32A42252AA84)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(91E4DC16-7872-4366-A9C2-106D5482A829)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(70D2A708-272C-435C-8AA7-BA2A76EE6863)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(4AC0D924-A0B6-4773-96CD-01320CEE6986)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(29196B8D-873B-4584-8F2D-BDCD5852BF8F)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(BE1BFFD1-F3E4-4285-93EF-71986FDE1A2D)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(D8B7F85A-B248-491D-882C-6CC6162AB83B)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(0BA61E2B-E1CE-45E7-A752-174DC73DE799)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(5EF6F453-1BFB-4780-8281-8DB76CA89061)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(0F5155DB-755B-428B-9235-D7C94EEF7589)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(18F25E34-25C4-46F7-9953-B06C422CDF4D)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(26F96482-BAC0-4198-9D8C-4807FEC57C6C)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(65DFF22A-9CF5-4835-8CCB-52B3574E4F96)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(8BE703DA-023F-4DA4-AB8B-5291EA721A6D)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(637F74F4-EC6B-4645-9818-599A5B968515)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(D178CCB9-DBF4-4471-B31F-236271A23A2D)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(B3FC29CA-E61D-48CD-A4E8-99ED9199E479)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(A3D48FBC-DCDB-4078-9CC3-70309722222C)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(7758F7FF-53E7-4BB1-84B3-ABD7569ADC00)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(0D245588-E624-45ED-B385-DCA0F5EFDF9A)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(4619C941-1079-4176-B971-7C6E21BE7693)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(2B5B30C5-83D9-42FA-8E1B-14B1D1C24F9C)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(0EE41C50-59AA-4E10-8082-A727552B6213)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(7F8AEB1E-1226-4424-8653-83E6993DC24C)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(F6CBE0FD-8EB7-42EE-9E3A-B2CCBFF51C98)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(56E43F12-290C-4C7C-A0E9-3E4072D88955)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(8F79FB8A-90CD-4F4B-A79B-A564ACACAEF4)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(0CECDF64-C53A-4F93-814D-4EC0D94B35BD)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(D185FF7C-EE69-4C92-A59E-454B78B4F5DD)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(972025A9-D907-421D-94FE-991C80FCFC1F)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(339074E6-8A06-4609-8559-6C5992FE3675)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(AFF03370-6611-4723-9BC1-8254D9728B7D)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(FDA624BD-A1FB-4599-B827-CBC5420C8B06)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(8ADE0324-1E12-449B-823F-21088BFB165D)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(8BD40867-6B85-4749-A8DA-4372AAA00397)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(1794B948-8851-49DD-8E0C-14141560AD44)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(FF0C2465-681C-4C0A-A6CE-F221927B60FC)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(C02A4127-38EC-49E5-BCB9-3759DC5EA2AD)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(3A0A8BA3-11F9-4F90-815A-01AD072CD007)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(45E58FB8-2BE9-4EBD-891A-B25F3FFCEB61)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(01A0A19C-E37E-4BB4-AB28-37B4862472B6)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(E474C9AF-85E0-485B-B1EB-79A5BCB7DC9B)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(35E6CCA4-56FB-4EF8-B275-236772D3EA7D)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(7330313A-6072-4F55-B328-AD9866C015F3)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(1B871001-37CF-45CC-BF1A-F167490D065D)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(EA6D8130-C5E5-4982-9F30-814FFEA16857)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(FAC1E10C-0F39-4C24-AD90-3DA0E995EE5D)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(69C77DD0-EE39-4372-BF0F-D649431A6364)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(6E602C8E-1788-447A-9B36-B531B4AAA93E)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(AE7A6F96-8A00-47B3-A72D-8900C7C01E11)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(D61420E9-29C8-409D-921B-DE90966A2385)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(33D3A737-7BF5-4633-BF87-A7B4BC30BAA8)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(11F1D6E4-63AA-4754-8BAE-FA094B2EB16A)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(4DF97FE7-7B68-4A6C-8346-4C18FD81B299)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(7A756CBC-81E6-4F83-A204-6390F0E49C84)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(030360D5-168F-4690-B10F-250919B2AC0C)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(E7FF4D9B-5583-493B-9067-CF8C354ACB3D)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(9AEBE3B9-D118-49FE-98C1-90E47A861573)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(59E0E205-9196-49A4-9BDD-DD93C0FABBD6)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(B4A18381-17F4-4B10-881E-87EE08065B5A)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(D5998D69-8BB7-4B76-A76D-A518326EF183)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(4131F1F0-8F58-4A85-9728-17D1E8206A59)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(72B090B2-4641-4DAE-82E3-CBD252D86666)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(F1479046-2BAD-4F4F-AA3B-813FE77575BD)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(F0C51B4E-4FA9-4D76-95E1-61523E69458A)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(5BF5DB70-B8C5-4B04-B0F9-95D7AAAAFF7E)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(85F00BB8-B9B1-45C5-9873-03A5573826DC)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(349045F4-0102-4463-820A-F00D441749B2)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(9D8F8774-5AC5-42F6-898D-D1D72DC5CF94)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(7FCE8B9F-8F7F-4DA3-8A15-A92D77782F04)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(06DEA444-7922-4E7A-BCCF-224F316A6A37)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(BD5A39F7-2C06-408A-8476-72CD9BEA97DF)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(DC8368C5-F2C7-4C13-9DE5-E8C143514CEF)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(13F58636-F1F9-4009-9997-6F2C8EBA40D3)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(4323A1C2-5742-41CA-B6C4-353DAA464215)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(4E0BC360-603C-43BE-B2C8-8D11A7DEE1A5)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(72BCA040-0F12-4146-AC47-95585A1EC6D3)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(63427909-3B92-4404-899B-FAC01CDD5066)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(F6ED3F5A-F8E7-412B-96CB-CADAEC600E10)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(A36DB8AF-5BDB-4BE8-8F53-01A1F6F4223A)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(AA398041-1B62-4F8F-89AA-7BD6A5C8A20B)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(63B0DADC-44B2-4737-9C6C-BE5DF48A5A4B)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(45AE37B0-981E-4B3D-9252-13731C015E15)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(D1F06460-0578-4161-BC1C-1F7DFB14CF83)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(F20D4360-C2F8-4096-8B5B-1E78C9276FFE)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(E04737A5-6878-4352-8900-B883D39E1A84)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(49403E21-DF44-4845-B2F4-E65124EAF494)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(CFA35253-4363-420B-A584-D4C6C3047198)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(0F34C400-A20B-476E-8B28-8D4A011DF217)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(247007ED-BA8A-49AE-83D2-9520336ECEE0)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(026F7947-AB87-4762-8F68-39A0FF80BEE0)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(ABC3F5F3-AE07-4F7E-950B-261AAFA04A5F)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(A48F564C-EB61-48AE-B0A4-9021B3BA478D)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(7F978A0F-8656-436C-A2A5-7F521AF643D4)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(4A5889BD-E2A1-46F8-9D78-E1EC321A3AF0)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(5720E9FF-F665-4151-8EB9-D5EA38D6D987)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(34876826-FD79-4127-9B3A-A7D3826ABF81)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(C4C0F8D8-DF7D-4BD7-BAF2-0B0DFC97A965)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(D5E54562-8F1C-422F-9096-583E69D77E78)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(A6F9A7BE-257C-4C9D-85EF-BED6C605AE82)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(07CF7A6C-84A1-4AAC-A012-9F6FFBB46FFB)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(1CD29281-61DE-4A2C-A343-86844990CD40)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(80751990-24B9-4080-9F3E-3FCB7EC4E196)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(857EF3D0-8D42-4D4C-902D-E516DD6C4B96)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(98EEC16F-A36E-43AD-9703-CBA27755C361)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(8B1EFE32-91AE-4675-A668-F5BCB91B6585)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(F61BB1B9-5FD1-435B-9CCA-E445D5FC0185)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(1DE795DC-CD25-486D-BB87-419EB9ED8C50)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(E3A10A04-D32E-4FA9-9920-4831B63905FB)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(462A5534-3050-4754-B2B0-7005E1F2253D)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(973D67F5-310F-4915-96C6-E573E7D42290)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(7AF03202-0A7A-4E0E-8B40-B10ECFD6AE2E)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(5DB51C37-80DA-437A-83B9-9FCBBA2C6811)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(D39BD353-0A54-498A-867F-FEF8145A9F6E)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(0D29D245-8DCB-4571-A14A-0D76FA4B7382)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(D0E6E86F-7FD0-456C-8B27-A903EDDAE554)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(CFE04DCA-38FA-4722-BF15-4F2A7890DF47)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(FB13A4E7-C6CB-49B6-8751-B16CB908E3CC)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(9146124B-7F40-4A23-893B-D28C7CC9FD10)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(4EC380E8-2E5E-4239-A020-E4CECA848860)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(C43B27B5-55D9-4419-9D0F-D8976D1C57C5)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(AAB186F0-2FC5-43F1-91CD-BD5D31936664)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(E112CC86-8213-4541-B260-AC8789F6C400)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(7B5EEB5C-40E9-4F1A-9204-76E496A93C79)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(318EC1E4-5A9D-4782-AC5E-CDDB49F54F51)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(71DCB4A5-1098-4224-9C5F-2EDBAA4558D0)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(3DCD2A2D-891C-425E-8540-9356B3A2FBBE)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(91D6B219-CF04-44A2-8940-6D01BD791B68)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(8EA6829C-6D19-46FB-B051-3E2507D073C3)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(32BBB712-3775-4DAC-92DA-70C582A6AA0E)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(360DFCE8-3935-43CE-A376-985D9BB30406)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(5B510DEA-2F43-42BF-9262-A443280BD993)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(B12F6331-2987-43DD-9874-E4757B9DF82B)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(9494C04A-6BA4-4369-8BF2-2946F481AAB6)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(C391989A-407E-4642-B97B-62474D7F35D7)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(B474D75F-535A-4DA5-88BA-C0CE4DD8BFC7)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(B55CE2F5-3190-43F3-BE27-74B45D3F787A)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(39968FCE-DFE5-4127-9348-9103C003227B)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(65347C5C-9628-4DD9-9311-C6876261CF33)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(3F993E01-0932-436E-AC73-D90DB72C91D9)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(CF478659-B754-4402-8BDB-FB1DF8F99C0E)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(6740A112-32A8-4777-9FC6-D88FED468A1C)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(12AE4174-A723-42F0-9EF2-E14CE5CA8EA5)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(FEF8D550-5905-476D-B17B-953C548C69E7)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(216656D4-5E38-47CA-945C-B86CDADAEA2D)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(C45535D7-C983-433F-ADAF-ED95BB648C79)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(AC9FA692-6F3C-4488-9F8A-F42BAAF05BEB)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(1879C994-BF69-433C-A7BE-7873D7EF69FE)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(1237773D-09B5-45B0-8A95-CE5EE31A11FC)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(CAE25CCF-F105-4E5D-94AB-43984AC291FF)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(3B2F3C1C-4B3D-4E6B-90C9-F2262A8375B6)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(49A436B5-7FCC-4EEE-94D2-6A9C2088AD8A)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(9334B3D8-8B84-4F72-9C47-59141495962A)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(790CC70D-475C-4DE4-88DB-49BDAED29F4A)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(A6716A94-8949-4CE8-BE77-4696B6671E5D)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(19E8663D-9FDE-4380-934E-EC7803CD6619)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(4671EA36-148E-4AE0-9548-7D01739AADD7)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(40704C2F-0877-458A-8196-7E742DDBBA69)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(67FFFA09-897F-49CD-AB34-3F9D5B196123)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(A57BAE64-9132-4F1D-B268-A60D2D5C0100)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(793729C1-5F19-4043-B564-1708C48B898A)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(0089298A-9A55-4FB0-A129-74AF9CAC1590)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(90E77C32-4992-479E-B229-8C9DDCAF1F1F)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(0379FA80-75C2-4E0D-A2CE-B1B1469E9A2C)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(FFD320B6-9FF6-4765-B427-90A2AED42163)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(D74F2A75-4402-4B6B-8FF6-9AFD8DDB132F)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(9DBC62BF-F506-4D67-8A70-8992F15BA753)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(26FC0239-7B2E-4A46-81B0-DDA273FBE6D3)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(E80DD3C3-4758-4B0E-94C5-DD5573975028)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(05EDDA1D-38D6-4E94-AE08-F635439DDD7C)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(195FA8D3-BCB6-4308-AC78-1013B8EAC064)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(8C01E1D9-0A1E-491B-939E-DCDB6627B1C5)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(C2E57D5D-3C4D-4324-A77F-926D465E35F1)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(9DBAE5B5-EF0C-457E-A352-4AB1A5A6F9EA)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(6D2F7B97-B0F8-4763-8C96-77B010143485)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(96C5A641-1380-4AAE-B453-53E51F282406)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(43962EF8-4266-4F77-8B29-DC2A85E879D8)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(50FA1B5C-5D03-4DDE-ADFF-6685A30E708C)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(0D0C87DB-9570-4D59-8B8B-0FA1A9179C17)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(4F0B9C26-5DC8-4FDE-9F5D-98429CCBC7DB)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(4D0FB842-5C43-4B8B-B141-4A5217CE0126)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(A86D52B9-A060-42D2-ADF2-B684FEC35195)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(EAAA974D-AB1F-4C50-8160-BAEF920E838C)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(F001422E-A504-422F-8C36-8F219D288B33)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(2036F6EA-79C4-4F8B-A1C0-92F6907A49BE)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(648A7561-72B9-407B-9BD4-D1F71AA7A21F)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(50483EAE-E7D8-4328-AFD7-F84CA1020FF0)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(6B52CD47-AF1A-470D-A079-CA12A41DBD84)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(E1A82D76-1D6B-40DF-A95C-CF4669F00C66)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(597F49F0-D34D-4776-833D-A09FEFBED47C)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(A1FDEEDF-5981-4653-BE7B-84AD811B82F8)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(9B6175BA-D59B-4969-8AF8-2C9AD43AC60F)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(E81C23A0-EF78-45D5-8F59-C5E2FE51E3FD)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(DFE00229-95A8-470D-832C-AD43B4733F39)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(A87895FE-CB65-4E64-9ACF-37606F6F9878)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(DB1D5709-E2DD-4279-8FF8-D7B45C3B21D2)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(22F642DA-3F7E-42D4-A488-9D2705D37FCE)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(93C5C540-AD69-4DCF-8DC6-079BDB5CF758)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(3D0D7112-9654-46C4-ABC1-2921BB1A63C0)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(341AA828-0DCC-4DD9-A8EB-4631D4319F72)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(2366C9EC-8471-4B3F-9F29-ED686C1A45FD)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(C22AC3B0-EE4B-48B7-AB91-D974270CB929)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(7C249470-A4AB-4340-848D-F780090C022D)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(253AD08F-44B5-4514-8C42-D5D33A478A94)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(11918938-A3F8-4031-B7BD-66CFD5D4C51C)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(8E10854E-DD98-4FB0-BC34-67962A783638)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(3A5954C3-8E63-4E6B-A92B-DFE31099C4E3)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(CB284643-7D21-44D1-B179-D7E307C13D7D)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(9B30B959-AF7A-4EFC-9E80-C7CFDF24E8AD)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(09F081FB-1CB8-4343-AF7F-D680DED2BCCC)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(D8E2C4C7-BAC8-4A0B-8228-7193A4F247F2)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(AFD6C771-7275-46C7-AF05-1383AB48ECC3)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(6FBBE2E0-737F-4CE9-BB48-8236134B7449)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(16AB4CEE-7DAB-42E4-BD18-766991025365)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(E132CB65-1502-4607-8687-AC1EC3078E60)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(394FC287-421B-41F2-A492-C73FC06D665F)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(CA736FAE-F9B7-4CD3-A9DC-A3837E7B9A76)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(3E9028A4-B354-45FB-8DE5-F988747F1576)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(5E92B8AE-6E63-47FE-9EC4-EB6F30F43CE7)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(2699E1A4-27BB-4903-9C5F-77C75238BB79)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(58440F7D-99E9-4FEC-91EA-B002C2F142A9)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(B938E58D-D6E3-4EAF-8840-B6D94339EAF0)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(89DBB1C0-6DF9-42FE-A5FE-B70C7061DB7B)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(B5732F7E-BECB-4820-9D0F-ECABA9A39C73)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(6A0C7D51-41C9-4AB6-9970-0221E31A195C)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(178F0836-C6C6-4DB7-B0D0-D47B54B42615)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(4F3CE6B7-37CA-4775-8E63-F9687ECD9773)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(B2EBEFFE-2E98-4E6B-B775-9F2493A499BC)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(428DC595-A5AB-4E04-AA27-42A16C6F140D)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(87EF65D5-49A3-4C92-8416-E1A63A10D6F9)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(0FD2F9F3-0460-453C-ADC5-A88A1BAEC3D6)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(A3AA699C-AC5E-476D-A331-44832F5CC65F)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(34D86536-7361-44F6-8277-70E334E8C3CF)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(D35CDF8A-6063-4BD4-A94A-9FE7B937E553)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(61F7E5F4-6560-4F5D-B5F3-20C616164556)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(BEFAF4FA-C5C0-47C9-BE50-A4FA434B0090)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(6129E7B9-BC47-4608-8F24-641B2C1DB73F)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(093F4C03-8589-4314-906C-60DC40F6B4AE)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(08633F51-E6A5-45A7-891F-BA2632D0AAB3)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(406B0F63-515E-4277-AB6A-5654CC18CF16)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(E5E03A5B-6622-429C-A22E-C1DF03850948)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(D0431B6D-73FA-4B53-9E2D-B65D6C94B8F6)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(AAA74468-DEC5-4C46-95B9-780A2A2D4FEF)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes["预设值(D079F42C-6687-470B-AF6B-9F532A7618C4)"].geometry
            }
            material={materials["Paint Matte Black #1"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/mono_willinsert.glb");
